### ISSUE TITLE
When token is revoked, no alert is posted in the channel set for token expiry alerts

### ISSUE THREAD

**Issue by louis6321** [CataIana/twitchcommandbot#3]
The bot just keeps trying to connect to the channel and fails over and over

**Comment by CataIana** [comment]
This should be fixed in the latest commit

**Comment by louis6321** [comment]
![NtSn0wzfQx](https://user-images.githubusercontent.com/43100308/168462705-5bf4d263-16af-4dc2-a447-0e712e004150.png)
The bot is definitely handling the revoking of the token a lot better, but it's still not posting a message that the token is revoked in the defined token expiry channel.

**Comment by louis6321** [comment]
Fixed now, ty
